name: memento_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #notification
  flutter_local_notifications: ^6.0.0
  timezone: ^0.7.0

  #maps
  google_maps_flutter: ^2.0.6
  flutter_polyline_points: ^1.0.0
  geolocator: ^7.0.3
  geocoding: ^2.0.0

  #internet
  http: ^0.13.3
  uuid: ^3.0.4



  #Float action button
  flutter_speed_dial: ^3.0.5

  #Ajuda com o uso de SVG
  #  flutter_svg: ^0.17.4
  cupertino_icons: ^1.0.2
  intl: ^0.17.0

  #Ajuda com o state management
  shared_preferences: ^2.0.5

  #Cuida dos tamanhos fixos e fontsize para serem responsivos
  flutter_screenutil: ^5.0.0

  #Icone Config
  font_awesome_flutter: ^8.10.0
  community_material_icon: ^5.4.55

  #Auto complete (Ainda não foi implementado)
  flutter_typeahead: ^3.1.3

  #Database SQFlite
  sqflite:
  path:

  #Dependencia e Arquitetura (MobX)
  auto_size_text: ^2.1.0
  flutter_modular: ^3.2.1
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0

  #calendar
  table_calendar: ^3.0.0

  #calculate_age
  age: ^0.0.1





dev_dependencies:
  flutter_modular_test: ^1.0.1
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3
  build_runner:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: MementoIcons
      fonts:
        - asset: fonts/MementoIcons.ttf
  # To add assets to your application, add an assets section, like this:
  assets:
    - images/intro1.png
    - images/intro2.png
    - images/intro3.png
    - images/profile_sample.png
    - images/add_activity.png
    - images/add_bf.png
    - images/add_medicine.png
    - images/map_gif.gif
    - images/map.png
    - images/avatar.png
    - assets/map/map_style.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  #slidy shortcut
  # - slidy run build
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner

scripts:
  full_build: $clean & $get & $runner build --delete-conflicting-outputs
  build: flutter pub run build_runner build


#  killall "Simulator" 2> /dev/null; xcrun simctl erase all
#  xcrun simctl shutdown all && xcrun simctl erase all

